# Created on 2017-10-18T13:38:47.161
org.testng.TestNGException: 
Two tests in the same suite cannot have the same name: test1
	at org.testng.TestNG.checkTestNames(TestNG.java:1057)
	at org.testng.TestNG.sanityCheck(TestNG.java:1044)
	at org.testng.TestNG.run(TestNG.java:1108)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:373)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:334)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:119)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:407)


